import React, { useState } from 'react';
import { List, Spin } from 'antd';

const MemberList = ({ listOfMembers }) => {
  /*listOfMembers = [
        "SZr3okTZC5",
        "URdYPfyMXs",
        "5o0YOuLRPT",
        "GVyH4N1yPM",
        "mibuMWdKN2",
        "179i8E7Nrg",
        "mpl8tmi8SW",
        "4CZxXZrP2L",
        "fhI1oatLsR",
        "3F1Ne6MEGB",
        "ecfPaw5rnT",
        "9MBgS1BNtX",
        "xAU9dymXdn",
        "MCZStj51hQ",
        "RXfIMH4d4d",
        "pbycD57eQe",
        "PCmf8eBy8O",
        "FUSlAyTU6V",
        "1Xx4NUme3C",
        "KQ6Rp6RmyP",
        "6y9C7UCMtp",
        "rWqgaSFNsx",
        "CnBfIgPF43",
        "mseg8saJtU",
        "YwIaLz8oMl",
        "tWvrP7Lja0",
        "2lQbHTlQqc",
        "GqgwPfOWvO",
        "yj3QVMQGzg",
        "U4mqaoVyDz",
        "cu62mxHDWI",
        "U02DPp3qIf",
        "jSEOri0aF4",
        "jzrslt7H5Z",
        "svLE7z3ztf",
        "a6KNoHApLb",
        "vcYaM4Rcca",
        "5OSQJWn7Oq",
        "FuMuHsxt33",
        "IIwISE5x72",
        "XwhVY2t5Zw",
        "cuW0HfxJqh",
        "4jrBNop2Cr",
        "scBjpj7n6k",
        "U9WqfEvO9C",
        "81GzClwE6Y",
        "rrKVfeOrUX",
        "YiC9hizyqx",
        "x1lF2PnNa4",
        "WIQvnDYd7v",
        "QGbhqqZe0e",
        "4QabGVpTL1",
        "1C0bIp8mwO",
        "2O29YB4w8S",
        "lrAxHSt62g",
        "58ViJtN8sT",
        "kbpNLMM8q1",
        "Sf07lgLIAK",
        "Y1oZUt0W9E",
        "UbR4Gr0pCp",
        "UVcIYzFc90",
        "ZscOksqzZi",
        "a3f0ymYLwk",
        "fJfWLfNfao",
        "krZQuQTsMq",
        "YDlNqKeKb2",
        "JUtfGzEvaG",
        "9pGL9v5GjQ",
        "vqELAlB6CM",
        "rXYYt6rraw",
        "Nd7uFOqId7",
        "vmtLRKn0V4",
        "oU4s25fykI",
        "0uL9piOUbQ",
        "0eaO0GgJoI",
        "eanqK2IvlB",
        "YSMMW6cRO1",
        "skh8tQuD5i",
        "apMzErPyHb",
        "Bs0SB0JDN3",
        "9CnuaYVaN9",
        "aaydmjo0rK",
        "DbsdGKE4eu",
        "al6rNVeER8",
        "Uhvq6KEgev",
        "1t8oAcc6cP",
        "e6yobuPwfY",
        "KK7y4Vlhos",
        "PoK8YbkA6D",
        "Z71LyZ5hPN",
        "4nqtG2Yyi4",
        "8zZGFu2FuL",
        "WwFrS4VT9Y",
        "JoTfLB34J4",
        "HLe1KpZuI4",
        "lKUQFOC9EI",
        "Xm6kTcVaYC",
        "VVc3SFo26R",
        "gcea0u1zR6",
        "CEGEYb69y4"
    ];
    */
  return (
    <List
      grid={{
        gutter: 16,
        xs: 1,
        sm: 2,
        md: 4,
        lg: 4,
        xl: 6,
        xxl: 3,
      }}
      dataSource={listOfMembers}
      renderItem={item => (
        <List.Item>
          <List.Item.Meta title={item} />
        </List.Item>
      )}
    />
  );
};

export default MemberList;
